version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: